spec/amadeus/namespaces.test.js, src/amadeus/namespaces/travel/analytics.js, src/amadeus/namespaces/travel/analytics/air_traffic.js, src/amadeus/namespaces/travel/analytics/air_traffic/traveled.js
- Add new Traveled class
- Rename AirTraffics to AirTraffic
=> Fix Most traveled destinations API

CHANGELOG.md, README.md, package.json
=> Release version 1.0.0

README.md, package.json, spec/amadeus/namespaces.test.js, src/amadeus.js, src/amadeus/namespaces/reference_data.js, src/amadeus/namespaces/reference_data/airlines.js, src/amadeus/namespaces/travel/analytics/air_traffic.js, src/amadeus/namespaces/travel/analytics/air_traffic/booked.js, src/amadeus/namespaces/travel/analytics/air_traffic/busiest_period.js
Add endpoint implementations for the new following APIs:
- Airline Code LookUp
- Flight Busiest Traveling Period
- Flight Most Booked Destinations
=> Add new endpoints

package.json
Update documentation package version.
=> Update dependecy version

README.md
Replaced client_id and client_secret by API_KEY and API_SECRET
Fixed typos and updated examples to be aligned with our portal + other SDKs
=> Update authentication doc and examples

src/amadeus/client/access_token.js
https://github.com/amadeus4dev/amadeus-node/issues/22
=> Fix bug #22: token expiration time wrongly calculated

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/travel.js, src/amadeus/namespaces/travel/predictions.js, src/amadeus/namespaces/travel/predictions/flight_delay.js
#46 Add support Flight Delay Prediction
=> Add support Flight Delay Prediction

README.md, spec/amadeus/namespaces.test.js, src/amadeus.js, src/amadeus/namespaces/media.js, src/amadeus/namespaces/media/files.js, src/amadeus/namespaces/media/files/generated_photos.js
#45 Add Support for AI-Generated photos
=> Adding support for AI-Generated photos

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/shopping.js, src/amadeus/namespaces/shopping/flight_offers_search.js
#30 Adding support for Flight Offers Search API
Fixes #
Property names in shopping.js
=> Adding support for Flight Offers Search API

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/shopping/flight_offers.js, src/amadeus/namespaces/shopping/flight_offers/flight_choice_prediction.js
#64 Decommission LFS, Update Flight Choice Prediction v2
=> Decommission LFS, Update Flight Choice Prediction v2

package-lock.json
Fixes #
Dependencies:
- `npm audit fix`
- github security vulnerabilites
=> npm audit fix 2

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/shopping.js, src/amadeus/namespaces/shopping/activities.js, src/amadeus/namespaces/shopping/activities/by_square.js, src/amadeus/namespaces/shopping/activity.js
=> Add support for Tours and Activities API

CHANGELOG.md, package.json
=> Release version 5.5.0

README.md
=> Update outdated dates on readme

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/shopping/flight_offers.js, src/amadeus/namespaces/shopping/flight_offers/upselling.js
Fixes https://github.com/amadeus4dev/amadeus-node/issues/106
=> Branded Upsell Offers

README.md, src/amadeus/namespaces/reference_data/locations.js, src/amadeus/namespaces/reference_data/locations/airports.js
=> typos fixed and update examples.js

spec/amadeus/client/request.test.js, src/amadeus/client/request.js
add HTTP override method for 6 endpoints
Thanks you @gustavo-bertoldi  for big helps!
=> add HTTP override

README.md, spec/amadeus/namespaces.test.js, src/amadeus.js, src/amadeus/namespaces/duty_of_care.js, src/amadeus/namespaces/duty_of_care/diseases.js, src/amadeus/namespaces/duty_of_care/diseases/covid19_area_report.js
Added support for the Travel Restrictions API, associated tests and call example in README.md
=> Add Travel Restrictions API

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/shopping.js, src/amadeus/namespaces/shopping/hotel_offer_search.js, src/amadeus/namespaces/shopping/hotel_offers_search.js
Add Hotel Search V3, and keep Hotel Search V2
=> add hotel search v3, keep v2

CHANGELOG.md, package.json
=> Release version 6.0.0

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/reference_data/locations.js, src/amadeus/namespaces/reference_data/locations/hotel.js
add hotel name autocomplete API
=> add hotel name autocomplete

README.md, spec/amadeus/namespaces.test.js, src/amadeus/namespaces/duty_of_care/diseases.js, src/amadeus/namespaces/duty_of_care/diseases/covid19_report.js
Add Travel Restrictions v2 #159
=> add travel restrictions v2

.github/workflows/build.yml, sonar-project.properties
=> add sonarcloud in actions

README.md
There was a text line without been proper commented
Fixes #
Remove this if you have done all of these:
* Ensure all tests pass and linting
* Add any changes to the README
* Add any changes or new comments to SDK methods
* Ensure this PR only changes what it is intended to change
=> minor fix: comment a line of text in examples

spec/amadeus/client/pagination.test.js, src/amadeus/client/pagination.js
Pagination was not properly working because the code assumed the page offset in the URL was always the last which is not the case. Changed to extract exact the code page offset from the URL.
=> Fix pagination issue

CHANGELOG.md, package.json
Add support for [Travel Restrictions API v2](https://developers.amadeus.com/self-service/category/covid-19-and-travel-safety/api-doc/travel-restrictions/api-reference)
Fix pagination issue 
Add [SonarCloud](https://sonarcloud.io/) support
=> release 7.1.0

CHANGELOG.md, package.json
Reverts amadeus4dev/amadeus-node#178
publish not working
=> Revert "release 7.1.0"

.github/workflows/publish.yml
Fixes #
Remove this if you have done all of these:
* Ensure all tests pass and linting
* Add any changes to the README
* Add any changes or new comments to SDK methods
* Ensure this PR only changes what it is intended to change
=> fix publish.yml

CHANGELOG.md, package.json
Decommissioned Travel Restrictions API v1 
Decommissioned Hotel Search API v2
Fixed #174 SDK reference documentation is back
Fixed #183 Update comparisons in condition statements
Minor updates in How to Release in contribution guide
=> Release version 8.0.0

spec/amadeus/client.test.js, spec/amadeus/client/response.test.js, spec/amadeus/namespaces.test.js
Fixes #69
Adapted/Added tests to plug holes in the code coverage
- Missing tests for the `Client.delete` method.
- Reorder tests and check all returns to include all branches of the of `Response.parse`.
- Missing test for `trip_parser.js`
- Missing tests for `flight_order.js`
=> Improve code coverage

CHANGELOG.md, package.json
Add support for the [Transfer Search API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-search)
Add support for the [Transfer booking API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-booking)
Add support for the [Transfer Management API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-management)
- Update the version in package.json
- Update the CHANGELOG.md with the new version
=> release 8.1.0

CHANGELOG.md, README.md, package.json
Add support for additional parameters with [Flight Offers Price API](https://developers.amadeus.com/self-service/category/flights/api-doc/flight-offers-price)
=> Release 9.1.0

CHANGELOG.md, package.json
Add support for the [Hotel Booking API v2](https://developers.amadeus.com/self-service/category/hotels/api-doc/hotel-booking)
=> Release v10.1.0
